### ISSUE TITLE
Visiting Speaker from VLSCI, Melbourne speaking on HiPLEX

### ISSUE THREAD

**Issue by methylnick** [smilefreak/studyGroup#10]
Bernie Pope from VLSCI, Melbourne (NeSI equivalent) will be in Dunedin and will give a talk. He is also available for one on one meetings. 

When: 2015, September 28, 12pm
Where: Seminar Room, Centre for Innovation Building, Dunedin. [Map link.](https://www.google.co.nz/maps/place/Centre+for+Innovation/@-45.863558,170.5151145,17.09z/data=!4m2!3m1!1s0x0:0x55fa3d7a8f52e0c5)

This event is an open forum, all interested are welcome to attend.

**Comment by methylnick** [comment]
okay hit a stumbling block, I have proposed a new file, but didn't update the issues url which is this.

https://github.com/smilefreak/studyGroup/issues/10

hmmmm it's all gone! I am still a newbie when it comes to git!!!

Cheers

Nick

**Comment by methylnick** [comment]
Here is Bernie's workflow and would be more interesting to you now! 

http://www.hiplex.org/index.html

**Comment by methylnick** [comment]
Can we change the label on this discussion? it seems I can't administrators?!?!?!@?@

**Comment by smilefreak** [comment]
Hi Nick, 

Can you change labels etc now, I have made you a collaborator on the repo :)

**Comment by methylnick** [comment]
Great looks like we are getting there :-) thanks!

**Comment by methylnick** [comment]
Success!!!!!!!!!!!!!
