### ISSUE TITLE
Lightning SYSKA 22nd Oct

### ISSUE THREAD

**Issue by TomKellyGenetics** [smilefreak/studyGroup#19]
Topic ideas to be discussed at HackyHour today. Forum for topic suggestions and checking speakers don't repeat each other too much. More info soon.

New format this time. 5 speakers, 5 min each. Quick intro to gauge interest in future sessions.

**Comment by murraycadzow** [comment]
Think I just beat you to the submit button Tom

**Comment by TomKellyGenetics** [comment]
This issue was moved to TomKellyGenetics/studyGroup#8
