### ISSUE TITLE
Work along: ggplot2 10th of september 2015

### ISSUE THREAD

**Issue by smilefreak** [smilefreak/studyGroup#2]

**Comment by murraycadzow** [comment]
If you want to work along on your laptop make sure you have R/Rstudio and ggplot2 (and dependencies) installed

**Comment by BillMills** [comment]
Looks great folks - don't forget to put a where / when in the top post (admins can edit later if need be) so people know where to show up! Something like

> **Where**: Leith Room, Staff Club (address, map?)
> **When**: 3:30 PM September 10

(I know this was in your website listing, but never underestimate people's ability to not notice :)

I also like to throw cut-and-paste setup instruction in for newcomers:

> - Grab the free version of [R-Studio here](https://www.rstudio.com/products/RStudio/) if you don't have it already.
> - Once that's installed, install `ggplot2` by typing: `install.packages('ggplot2')` in the console. If you have trouble, drop in a few minutes early and we'll help you set up! 

Or something to that effect. Let me know how it goes, wish I could be there!

**Comment by murraycadzow** [comment]
This is a very useful resource for using ggplot2
https://www.rstudio.com/wp-content/uploads/2015/05/ggplot2-cheatsheet.pdf

**Comment by murraycadzow** [comment]
here is the code for the tutorial
https://github.com/murraycadzow/R_tutorials

**Comment by TomKellyGenetics** [comment]
Looking forward to it. I've brought a spare laptop in case anyone needs one, it's a Windows/Linux dual boot so should suit anyone. I think Anthony in particular may not have one.

Regarding the power situation, I've still got a spare multi-box and extension cord in the office from our last Software Carpentry workshop. I'll bring them if it helps while we arrange something more long-term.

Also, would it be possible to set up a 'click attending' function something so we have a ballpark figure of how many participants are coming?

**Comment by HannahLumley** [comment]
Currently in session! I enjoyed the party plot at the end of the lesson :)
