### ISSUE TITLE
Bernie Pope visitng Dunners and talking about HiPlex

### ISSUE THREAD

**Issue by methylnick** [smilefreak/studyGroup#9]
Hi All, just reaching out and touching base with you all about a friend and colleague that will be passing through Dunedin September 27-30. I am hoping to get him to give a talk at CFI at lunchtime (between 12-2pm either on th 28th or 29th, and then if you would like to catch up with him one on one, you are more than welcome to, get in touch with me. nick.wong@pacificedge.co.nz. His CV page is here:

http://www.berniepope.id.au/

Link to paper is:

http://www.biotechniques.com/BiotechniquesJournal/2015/January/Abridged-adapter-primers-increase-the-target-scope-of-Hi-Plex/biotechniques-356249.html

Look forward to hearing from you all and your thoughts, in particular, the time for a seminar. 

Cheers

N

**Comment by smilefreak** [comment]
Oh that looks great man, that time looks fine for me. 

For everone else, maybe bring it up today at the Study group, and then if we decide a time it would be cool to have the event listed on the website.

**Comment by methylnick** [comment]
Thanks James. Will make it an event.

**Comment by lastkarrde** [comment]
The seminar sounds good. Thanks Nick!

Logan

**Comment by methylnick** [comment]
Thanks Logan! will get onto it.
